from typing import List

from langchain_core.runnables import RunnableConfig

from app.orbitqa.state import OrbitQAState, RetrievedDoc
from app.rag import RetrievedChunk, Retriever, VectorStore


def retriever(state: OrbitQAState, config: RunnableConfig):
    """
    Execute vector database retrieval using generated queries and return relevant documents.

    This function performs the actual document retrieval from the RAG system's vector
    database. It takes the search queries generated by the retrieve module, executes
    semantic search for each query, and consolidates the results into a list of
    retrieved documents with metadata.

    The function queries the vector database for each search term, retrieves the
    top-k most semantically similar chunks, and extracts the text content along
    with source information and approximate page numbers.

    Parameters
    ----------
    state : OrbitQAState
        The current workflow state containing:
        - data_query : list of str
            Search queries generated by the retrieve module.
        - retrieved_docs : list of RetrievedDoc
            Previously retrieved documents (if any).

    config : RunnableConfig
        LangChain configuration object containing:
        - configurable.vectorstore : VectorStore
            The initialized vector database instance (e.g., Pinecone).
        - configurable.top_k : int
            Maximum number of chunks to retrieve per query (typically 3-10).

    Returns
    -------
    dict
        A dictionary with a single key:
        - retrieved_docs : list of RetrievedDoc
            Updated list containing both previous and newly retrieved documents.
            Each RetrievedDoc contains:
            - text : str
                The content of the retrieved text chunk.
            - source : str
                The source document path or filename.
            - page_no : int
                Approximate page number (average of start and end pages).

    Notes
    -----
    The retrieval process:
    1. Iterates through each query in state["data_query"]
    2. Performs semantic search using cosine similarity on embeddings
    3. Retrieves top_k most relevant chunks per query
    4. Extracts text, source, and page metadata from each chunk
    5. Appends all results to the existing retrieved_docs list

    Page number calculation uses integer division: (page_start + page_end) // 2
    to provide an approximate location within the source document.

    The function does NOT deduplicate results. If multiple queries return the
    same chunk, it will appear multiple times in the output. Downstream modules
    should handle deduplication if needed.

    Metadata filtering is currently disabled (metadata_filter=None), but can be
    enabled to restrict searches to specific sources, date ranges, or document types.

    Examples
    --------
    >>> from app.orbitqa.state import OrbitQAState
    >>> from langchain_core.runnables import RunnableConfig
    >>> state = OrbitQAState(
    ...     data_query=["Hohmann transfer delta-v formula", "orbital mechanics basics"],
    ...     retrieved_docs=[]
    ... )
    >>> config = RunnableConfig(configurable={
    ...     "vectorstore": my_vectorstore,
    ...     "top_k": 5
    ... })
    >>> result = retriever(state, config)
    >>> len(result["retrieved_docs"])
    10  # 5 chunks per query × 2 queries
    >>> result["retrieved_docs"][0]
    {'text': 'The Hohmann transfer...', 'source': 'orbital_mechanics.pdf', 'page_no': 42}

    With existing documents:
    >>> state["retrieved_docs"] = [{"text": "Previous doc", "source": "old.pdf", "page_no": 1}]
    >>> result = retriever(state, config)
    >>> len(result["retrieved_docs"])
    11  # 1 existing + 10 new

    See Also
    --------
    retrieve : Module that generates the search queries.
    app.rag.retriever.Retriever : RAG retriever class for vector search.
    app.rag.vectorstore.VectorStore : Vector database interface.
    """
    vectorstore: VectorStore = config["configurable"]["vectorstore"]
    top_k = config["configurable"]["top_k"]
    vector_retriever = Retriever(vectorstore, top_k)

    retrieved_docs: List[RetrievedDoc] = []

    for query in state["data_query"]:
        query_specific_vectors: List[RetrievedChunk] = vector_retriever.retrieve(
            query=query,
            top_k=top_k,
            metadata_filter=None,
            include_metadata=True,
            include_scores=False,
        )

        for retrieved_chunk in query_specific_vectors:
            retrieved_doc = {
                "text": retrieved_chunk.text,
                "source": retrieved_chunk.metadata.source,
                "page_no": (
                    retrieved_chunk.metadata.page_start
                    + retrieved_chunk.metadata.page_end
                )
                // 2,
            }
            retrieved_docs.append(retrieved_doc)

    return {"retrieved_docs": state["retrieved_docs"] + retrieved_docs}
